### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by EnderAvaritia** [Rinkuto/koishi-app-chatgpt#1]
```
  2023-04-02 16:39:09 [W] session 樱田 樱田 喵一个
                        Error: Request failed with status code 403
                            at createError (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\core\createError.js:16:15)
                            at settle (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\core\settle.js:17:12)
                            at IncomingMessage.handleStreamEnd (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Rinkuto** [comment]
403可能是ip被封了吧，换个梯子试试？？

**Comment by EnderAvaritia** [comment]
> 403可能是ip被封了吧，换个梯子试试？？

换了一个日本的，还是403，后面的没变。
我浏览器能进得去啊。

**Comment by EnderAvaritia** [comment]
```
 
2023-04-02 17:15:12 [W] session 樱田，晚饭吃啥
                        Error: Request failed with status code 400
                            at createError (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\core\createError.js:16:15)
                            at settle (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\core\settle.js:17:12)
                            at IncomingMessage.handleStreamEnd (E:\Programme\koishi\koishi-desktop-win-x64-v0.9.4\data\instances\default\node_modules\openai\node_modules\axios\lib\adapters\http.js:322:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
这下又变成400了。
这里是开了v2的自动配置，koishi也开了，写的是v2的本地代理（http）。

**Comment by EnderAvaritia** [comment]
koishi里面关闭代理之后变成了这个。
电脑的环境是开了v2的自动配置代理。
```
 2023-04-02 17:17:37 [W] session 樱田，晚饭吃啥、
                        Error: connect ETIMEDOUT 162.125.80.6:443
                            at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

**Comment by Rinkuto** [comment]
v2不是很清楚，确定v2的代理端口写对了吗。刚刚下了一个windows的版本，没问题

**Comment by EnderAvaritia** [comment]
> v2不是很清楚，确定v2的代理端口写对了吗。刚刚下了一个windows的版本，没问题

我确定写对了，我看你还有个p站插件，那个工作……似乎正常的，你那边是怎么配置的？

**Comment by Rinkuto** [comment]
![image](https://user-images.githubusercontent.com/93482425/229345454-1a681d36-6f10-4bc4-9bb0-675ead3f98fe.png)
默认配置，如果你的代理是配置在koishi全局变量的话，是没有效果的，只能在该插件的配置中设置才有效果。
p站插件的话，其实不用翻墙也能访问。

**Comment by EnderAvaritia** [comment]
![image](https://user-images.githubusercontent.com/84321282/229345782-b6756784-ce2d-43ea-a010-535d6602381e.png)
![image](https://user-images.githubusercontent.com/84321282/229345794-b1f1c8c4-068a-41bc-b598-6abba2cec171.png)
![image](https://user-images.githubusercontent.com/84321282/229345935-69afce23-1262-4cc8-b8d6-cc141bc10f53.png)
为啥啊……

**Comment by EnderAvaritia** [comment]
![image](https://user-images.githubusercontent.com/84321282/229346046-51ce23d6-b47e-47f9-a179-0bf1d85e55ea.png)
艹……
我懂了……我开启了tun模式，它就有效了，会不会代理的语句有问题，它没走代理。

**Comment by Rinkuto** [comment]
> ![image](https://user-images.githubusercontent.com/84321282/229346046-51ce23d6-b47e-47f9-a179-0bf1d85e55ea.png) 艹…… 我懂了……我开启了tun模式，它就有效了，会不会代理的语句有问题，它没走代理。

这就不是很清楚了，~~毕竟我连tun模式是什么都不知道~~

**Comment by Rinkuto** [comment]
不过有用就行

**Comment by EnderAvaritia** [comment]
> > ![image](https://user-images.githubusercontent.com/84321282/229346046-51ce23d6-b47e-47f9-a179-0bf1d85e55ea.png) 艹…… 我懂了……我开启了tun模式，它就有效了，会不会代理的语句有问题，它没走代理。
> 
> 这就不是很清楚了，~毕竟我连tun模式是什么都不知道~

就是直接虚拟网卡（自暴自弃），clash也有，主页倒数第四个。

**Comment by EnderAvaritia** [comment]
> 不过有用就行

大佬……别呀，我服务器上没法开啊、

**Comment by Rinkuto** [comment]
> > 不过有用就行
> 
> 大佬……别呀，我服务器上没法开啊、

不是很理解，服务器上一定得开tun模式吗，我服务器上用的是clash，啥都没配置，都没配全局代理

**Comment by EnderAvaritia** [comment]
> > > 不过有用就行
> > 
> > 
> > 大佬……别呀，我服务器上没法开啊、
> 
> 不是很理解，服务器上一定得开tun模式吗，我服务器上用的是clash，啥都没配置，都没配全局代理

我服务器只要开clash必崩网络，至今查不出原因，要是开全局……上面还跑了个bt。
